Algoritmo "cal_100num"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 06/09/2024
Var
// Seção de Declarações das variáveis 
soma: real
x:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
soma:= 0
para x de 1 ate 100 faca
     soma:= soma + x
fimpara
escreval("a somo dos 100 numeros e de", soma)

Fimalgoritmo