Algoritmo "conversao_f_c"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 16/08/2024
Var
// Seção de Declarações das variáveis 
fharenheit: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
escreva("Digite os graus em fharenheit: ")
leia(fharenheit)
escreva("Os graus convertio seria ",(fharenheit - 32)*5/9 :2:2," graus celsius")

Fimalgoritmo