Algoritmo "exercicio3"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 12/08/2024
Var
// Seção de Declarações das variáveis 
Valor: inteiro
resultado:inteiro
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreva ("Digite um numero: ")
leia (valor)
resultado := valor+2
Escreval ("Resultado final é: " , resultado)
Fimalgoritmo