Algoritmo "N pares"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 13/09/2024
Var
// Seção de Declarações das variáveis 
x: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
x:= 1
    enquanto ( x <= 10 ) faca
             se( x % 2=0) entao
                 escreva
Fimalgoritmo