Algoritmo "jolonga"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 09/08/2024
Var
// Seção de Declarações das variáveis 
 nome: caracter

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva ("Digite o nome:")
leia (nome)
Escreva ("ola," , nome)

Fimalgoritmo