Algoritmo "rendimento"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 16/08/2024
Var
// Seção de Declarações das variáveis 
deposito: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreva ("Qual o valor do deposito: ")
leia(deposito)
escreva("Seu dinheiro rendera ", deposito * 0.007," reais")
Fimalgoritmo