Algoritmo "soma_num"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 06/09/2024
Var
// Seção de Declarações das variáveis 
num, soma: real
x:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
 soma := 0
 para x de 1 ate 5 faca
      escreval("Digite um valor")
      leia(num)
      soma:= soma + num
 fimpara
 
 escreva("A soma dos n° é ", soma)

Fimalgoritmo