Algoritmo "soma_repete"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 26/08/2024
Var
// Seção de Declarações das variáveis 
soma,x: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
soma:= 0
para x:= 1 ate 10 faca
     soma:= soma + x
     escreval("A soma dos numeros é: ", soma)
fimpara
Fimalgoritmo