Algoritmo "tabuada"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 06/09/2024
Var
// Seção de Declarações das variáveis 
i,n: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("Informe um n° para executar a tabuada")
leia(n)
para i de 1 ate 10 faca
     escreva(n, " x ", i, " = ", n*i)
fimpara

Fimalgoritmo